### ISSUE TITLE
Two tiny suggestions about c++17 and fa_solid_900.h, and a problem concerning `X` close button.

### ISSUE THREAD

**Issue by sirlis** [TyomaVader/ImGuiNotify#5]
1) Line 455 of `ImGuiNotify.hpp`:
```cpp
inline std::vector<ImGuiToast> notifications;
```
requires stdc++17, which I suggest to explicity informed in the README.

2) Line 26 of `ImGuiNotify.hpp`:
```cpp
#include "fa_solid_900.h"
```
don't know why I built with failure. Win11 with cmake, opengl, glfw, glad, imgui. I suggest remove it, seems to be of no use. Or do I made a mistake?

3) [Problem] My render result is as follows:

![image](https://github.com/TyomaVader/ImGuiNotify/assets/12960298/58e77c12-206c-46b5-9a76-89983d4b6632)

don't know why my `X` close button is so ugly.

When switching from `FONT_ICON_FILE_NAME_FAS` to `FONT_ICON_FILE_NAME_FAR`, the close button become `?`.

**Comment by TyomaVader** [comment]
Thanks for the issue

1. `README` will be updated.
2. Works for me on Win11, but yes, it's a useless file, `.ttf` is now used instead. Thanks for noticing!
3. Looks like all styles are set to default for you, have you disabled the EmbraceTheDarkness theme ? Make sure that `colors[ImGuiCol_Button]`, `colors[ImGuiCol_ButtonHovered]` and `colors[ImGuiCol_ButtonActive]` are set to the required colors. The `?` when using `FONT_ICON_FILE_NAME_FAR` is probably an issue with `FontAwesome6`, a few other icons are broken actually.

**Comment by sirlis** [comment]
> Thanks for the issue
> 
> 1. `README` will be updated.
> 2. Works for me on Win11, but yes, it's a useless file, `.ttf` is now used instead. Thanks for noticing!
> 3. Looks like all styles are set to default for you, have you disabled the EmbraceTheDarkness theme ? Make sure that `colors[ImGuiCol_Button]`, `colors[ImGuiCol_ButtonHovered]` and `colors[ImGuiCol_ButtonActive]` are set to the required colors. The `?` when using `FONT_ICON_FILE_NAME_FAR` is probably an issue with `FontAwesome6`, a few other icons are broken actually.

Thanks for your kind response. I will check if my theme is correct. Basically, I do not modify any theme related thing. I just introduced the original imgui into my project. Anyway, not a big deal.
